/**
 * RigPresets - Structures types de créatures pour tests et validation
 */
import { Creature } from '../types';

export const RIG_PRESETS: Record<string, Creature> = {
  // Preset 1 : Le Rig de référence 3 nœuds validé pour la Phase 1
  threeNodes: {
    id: 'threeNodes',
    name: 'Trio Organique (3 Nœuds)',
    schemaVersion: 1,
    nodes: [
      {
        id: 'n_body',
        name: 'Corps Principal',
        position: { x: 400, y: 340 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 1.2,
        radius: 32,
        isPinned: false,
        color: '#6366f1', // Indigo doux
        hasEye: true,
        behavior: { type: 'none' },
      },
      {
        id: 'n_head',
        name: 'Tête Suiveuse',
        position: { x: 420, y: 260 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 0.6,
        radius: 22,
        isPinned: false,
        color: '#38bdf8',
        hasEye: true,
        behavior: { type: 'follow_mouse', strength: 0.8, damping: 0.9 },
      },
      {
        id: 'n_tail',
        name: 'Queue Jiggle (Secondary Motion)',
        position: { x: 330, y: 390 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 0.4,
        radius: 18,
        isPinned: false,
        color: '#f43f5e', // Rose/rouge jiggle
        behavior: { type: 'jiggle', strength: 1.2, damping: 0.6 },
      },
    ],
    links: [
      {
        id: 'l_body_head',
        nodeAId: 'n_body',
        nodeBId: 'n_head',
        restLength: 85,
        stiffness: 140,
        damping: 10,
        width: 14,
        color: '#6366f1',
      },
      {
        id: 'l_body_tail',
        nodeAId: 'n_body',
        nodeBId: 'n_tail',
        restLength: 90,
        stiffness: 90,
        damping: 6,
        width: 10,
        color: '#818cf8',
      },
    ],
  },

  // Preset 2 : Chaîne 5 nœuds pour tester la propagation d'ondes et d'inertie
  chainWorm: {
    id: 'chainWorm',
    name: 'Chenille Ondulante (5 Nœuds)',
    schemaVersion: 1,
    nodes: [
      {
        id: 'c_0',
        name: 'Tête',
        position: { x: 300, y: 360 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 1.0,
        radius: 28,
        isPinned: false,
        color: '#10b981',
        hasEye: true,
      },
      {
        id: 'c_1',
        name: 'Segment 1',
        position: { x: 350, y: 360 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 0.8,
        radius: 24,
        isPinned: false,
        color: '#34d399',
      },
      {
        id: 'c_2',
        name: 'Segment 2',
        position: { x: 400, y: 360 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 0.7,
        radius: 21,
        isPinned: false,
        color: '#6ee7b7',
      },
      {
        id: 'c_3',
        name: 'Segment 3',
        position: { x: 450, y: 360 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 0.5,
        radius: 18,
        isPinned: false,
        color: '#a7f3d0',
      },
      {
        id: 'c_4',
        name: 'Queue',
        position: { x: 495, y: 360 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 0.4,
        radius: 15,
        isPinned: false,
        color: '#d1fae5',
      },
    ],
    links: [
      { id: 'l_01', nodeAId: 'c_0', nodeBId: 'c_1', restLength: 50, stiffness: 150, damping: 11, width: 14, color: '#10b981' },
      { id: 'l_12', nodeAId: 'c_1', nodeBId: 'c_2', restLength: 50, stiffness: 130, damping: 9, width: 12, color: '#34d399' },
      { id: 'l_23', nodeAId: 'c_2', nodeBId: 'c_3', restLength: 50, stiffness: 110, damping: 7, width: 10, color: '#6ee7b7' },
      { id: 'l_34', nodeAId: 'c_3', nodeBId: 'c_4', restLength: 48, stiffness: 90, damping: 6, width: 8, color: '#a7f3d0' },
    ],
  },

  // Preset 3 : Suspension avec oreilles/antennes à jiggle secondaire
  suspensionJiggle: {
    id: 'suspensionJiggle',
    name: 'Mobile Suspendu & Jiggle',
    schemaVersion: 1,
    nodes: [
      {
        id: 's_pin',
        name: 'Point d\'Ancrage Fixe',
        position: { x: 400, y: 140 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 2.0,
        radius: 12,
        isPinned: true,
        color: '#f59e0b',
        behavior: { type: 'none' },
      },
      {
        id: 's_body',
        name: 'Corps Suspendu',
        position: { x: 400, y: 260 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 1.2,
        radius: 30,
        isPinned: false,
        color: '#8b5cf6',
        hasEye: true,
        behavior: { type: 'none' },
      },
      {
        id: 's_ear_l',
        name: 'Oreille Gauche (Jiggle)',
        position: { x: 340, y: 220 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 0.35,
        radius: 16,
        isPinned: false,
        color: '#ec4899',
        behavior: { type: 'jiggle', strength: 1.5, damping: 0.5 },
      },
      {
        id: 's_ear_r',
        name: 'Oreille Droite (Jiggle)',
        position: { x: 460, y: 220 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 0.35,
        radius: 16,
        isPinned: false,
        color: '#ec4899',
        behavior: { type: 'jiggle', strength: 1.5, damping: 0.5 },
      },
    ],
    links: [
      { id: 'sl_pin_body', nodeAId: 's_pin', nodeBId: 's_body', restLength: 120, stiffness: 180, damping: 10, width: 6, color: '#f59e0b' },
      { id: 'sl_body_ear_l', nodeAId: 's_body', nodeBId: 's_ear_l', restLength: 70, stiffness: 100, damping: 5, width: 8, color: '#ec4899' },
      { id: 'sl_body_ear_r', nodeAId: 's_body', nodeBId: 's_ear_r', restLength: 70, stiffness: 100, damping: 5, width: 8, color: '#ec4899' },
    ],
  },

  // Preset 4a : Bipède Simple (2 Pattes directes sans genoux)
  bipedSimple: {
    id: 'bipedSimple',
    name: 'Bipède Simple (2 Pattes)',
    schemaVersion: 1,
    walkerConfig: {
      enabled: true,
      rootNodeId: 'bs_pelvis',
      bodyHeight: 110,
      walkSpeed: 540,
      anticipation: 0.12,
      legs: [
        {
          id: 'leg_l',
          name: 'Pied Gauche',
          hipNodeId: 'bs_pelvis',
          footNodeId: 'bs_foot_l',
          restOffsetX: -32,
          strideThreshold: 40,
          stepHeight: 32,
          stepDuration: 0.22,
          groupIndex: 0,
        },
        {
          id: 'leg_r',
          name: 'Pied Droit',
          hipNodeId: 'bs_pelvis',
          footNodeId: 'bs_foot_r',
          restOffsetX: 32,
          strideThreshold: 40,
          stepHeight: 32,
          stepDuration: 0.22,
          groupIndex: 1,
        },
      ],
    },
    nodes: [
      {
        id: 'bs_pelvis',
        name: 'Bassin / Corps',
        position: { x: 400, y: 390 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 1.3,
        radius: 28,
        isPinned: false,
        color: '#6366f1',
        hasEye: true,
        behavior: { type: 'none' },
      },
      {
        id: 'bs_head',
        name: 'Tête Couronnée',
        position: { x: 400, y: 325 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 0.5,
        radius: 20,
        isPinned: false,
        color: '#38bdf8',
        hasEye: true,
        behavior: { type: 'follow_mouse', strength: 0.6, damping: 0.8 },
      },
      {
        id: 'bs_foot_l',
        name: 'Pied Gauche',
        position: { x: 368, y: 490 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 0.45,
        radius: 14,
        isPinned: false,
        color: '#f59e0b',
      },
      {
        id: 'bs_foot_r',
        name: 'Pied Droit',
        position: { x: 432, y: 490 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 0.45,
        radius: 14,
        isPinned: false,
        color: '#f59e0b',
      },
    ],
    links: [
      { id: 'bs_link_neck', nodeAId: 'bs_pelvis', nodeBId: 'bs_head', restLength: 65, stiffness: 180, damping: 12, width: 14, color: '#6366f1' },
      { id: 'bs_link_leg_l', nodeAId: 'bs_pelvis', nodeBId: 'bs_foot_l', restLength: 100, stiffness: 140, damping: 8, width: 10, color: '#f59e0b' },
      { id: 'bs_link_leg_r', nodeAId: 'bs_pelvis', nodeBId: 'bs_foot_r', restLength: 100, stiffness: 140, damping: 8, width: 10, color: '#f59e0b' },
    ],
  },

  // Preset 4b : Bipède Articulé IK (Genoux)
  bipedWalker: {
    id: 'bipedWalker',
    name: 'Bipède Articulé IK (Genoux)',
    schemaVersion: 1,
    walkerConfig: {
      enabled: true,
      rootNodeId: 'bw_pelvis',
      bodyHeight: 120,
      walkSpeed: 620,
      anticipation: 0.12,
      kneeDirection: 1,
      legs: [
        {
          id: 'leg_l',
          name: 'Jambe Gauche (IK)',
          hipNodeId: 'bw_pelvis',
          kneeNodeId: 'bw_knee_l',
          footNodeId: 'bw_foot_l',
          kneeDirection: 1,
          upperLegLength: 65,
          lowerLegLength: 60,
          restOffsetX: -32,
          strideThreshold: 42,
          stepHeight: 34,
          stepDuration: 0.24,
          groupIndex: 0,
        },
        {
          id: 'leg_r',
          name: 'Jambe Droite (IK)',
          hipNodeId: 'bw_pelvis',
          kneeNodeId: 'bw_knee_r',
          footNodeId: 'bw_foot_r',
          kneeDirection: 1,
          upperLegLength: 65,
          lowerLegLength: 60,
          restOffsetX: 32,
          strideThreshold: 42,
          stepHeight: 34,
          stepDuration: 0.24,
          groupIndex: 1,
        },
      ],
    },
    nodes: [
      {
        id: 'bw_pelvis',
        name: 'Bassin / Torse',
        position: { x: 400, y: 370 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 1.3,
        radius: 26,
        isPinned: false,
        color: '#6366f1',
        hasEye: true,
        behavior: { type: 'none' },
      },
      {
        id: 'bw_head',
        name: 'Tête Expressive',
        position: { x: 400, y: 305 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 0.5,
        radius: 20,
        isPinned: false,
        color: '#38bdf8',
        hasEye: true,
        behavior: { type: 'follow_mouse', strength: 0.6, damping: 0.8 },
      },
      {
        id: 'bw_knee_l',
        name: 'Genou Gauche',
        position: { x: 375, y: 435 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 0.45,
        radius: 14,
        isPinned: false,
        color: '#f59e0b',
      },
      {
        id: 'bw_knee_r',
        name: 'Genou Droit',
        position: { x: 425, y: 435 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 0.45,
        radius: 14,
        isPinned: false,
        color: '#f59e0b',
      },
      {
        id: 'bw_foot_l',
        name: 'Pied Gauche',
        position: { x: 368, y: 490 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 0.5,
        radius: 13,
        isPinned: false,
        color: '#f59e0b',
      },
      {
        id: 'bw_foot_r',
        name: 'Pied Droit',
        position: { x: 432, y: 490 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 0.5,
        radius: 13,
        isPinned: false,
        color: '#f59e0b',
      },
    ],
    links: [
      { id: 'bw_link_neck', nodeAId: 'bw_pelvis', nodeBId: 'bw_head', restLength: 65, stiffness: 200, damping: 12, width: 14, color: '#6366f1' },
      { id: 'bw_link_thigh_l', nodeAId: 'bw_pelvis', nodeBId: 'bw_knee_l', restLength: 68, stiffness: 220, damping: 10, width: 14, color: '#f59e0b' },
      { id: 'bw_link_shin_l', nodeAId: 'bw_knee_l', nodeBId: 'bw_foot_l', restLength: 60, stiffness: 220, damping: 10, width: 12, color: '#f59e0b' },
      { id: 'bw_link_thigh_r', nodeAId: 'bw_pelvis', nodeBId: 'bw_knee_r', restLength: 68, stiffness: 220, damping: 10, width: 14, color: '#f59e0b' },
      { id: 'bw_link_shin_r', nodeAId: 'bw_knee_r', nodeBId: 'bw_foot_r', restLength: 60, stiffness: 220, damping: 10, width: 12, color: '#f59e0b' },
    ],
  },

  // Preset 5 : Quadrupède Procédural (4 Pattes en trot diagonal)
  quadrupedWalker: {
    id: 'quadrupedWalker',
    name: 'Quadrupède Procédural (4 Pattes)',
    schemaVersion: 1,
    walkerConfig: {
      enabled: true,
      rootNodeId: 'qw_chest',
      bodyHeight: 110,
      walkSpeed: 520,
      anticipation: 0.12,
      legs: [
        // Paire diagonale 0 : Avant-Gauche + Arrière-Droit
        {
          id: 'qw_leg_fl',
          name: 'Patte Avant-Gauche',
          hipNodeId: 'qw_chest',
          footNodeId: 'qw_foot_fl',
          restOffsetX: 40,
          strideThreshold: 42,
          stepHeight: 30,
          stepDuration: 0.2,
          groupIndex: 0,
        },
        {
          id: 'qw_leg_rr',
          name: 'Patte Arrière-Droite',
          hipNodeId: 'qw_pelvis',
          footNodeId: 'qw_foot_rr',
          restOffsetX: -38,
          strideThreshold: 42,
          stepHeight: 30,
          stepDuration: 0.2,
          groupIndex: 0,
        },
        // Paire diagonale 1 : Avant-Droit + Arrière-Gauche
        {
          id: 'qw_leg_fr',
          name: 'Patte Avant-Droite',
          hipNodeId: 'qw_chest',
          footNodeId: 'qw_foot_fr',
          restOffsetX: 65,
          strideThreshold: 42,
          stepHeight: 30,
          stepDuration: 0.2,
          groupIndex: 1,
        },
        {
          id: 'qw_leg_rl',
          name: 'Patte Arrière-Gauche',
          hipNodeId: 'qw_pelvis',
          footNodeId: 'qw_foot_rl',
          restOffsetX: -65,
          strideThreshold: 42,
          stepHeight: 30,
          stepDuration: 0.2,
          groupIndex: 1,
        },
      ],
    },
    nodes: [
      {
        id: 'qw_chest',
        name: 'Poitrail',
        position: { x: 440, y: 395 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 1.2,
        radius: 26,
        isPinned: false,
        color: '#10b981',
        hasEye: true,
        behavior: { type: 'none' },
      },
      {
        id: 'qw_pelvis',
        name: 'Bassin Arrière',
        position: { x: 350, y: 395 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 1.0,
        radius: 24,
        isPinned: false,
        color: '#059669',
        behavior: { type: 'none' },
      },
      {
        id: 'qw_tail',
        name: 'Queue Jiggle',
        position: { x: 300, y: 360 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 0.35,
        radius: 14,
        isPinned: false,
        color: '#f43f5e',
        behavior: { type: 'jiggle', strength: 1.6, damping: 0.5 },
      },
      {
        id: 'qw_foot_fl',
        name: 'Pied Avant-Gauche',
        position: { x: 480, y: 490 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 0.4,
        radius: 12,
        isPinned: false,
        color: '#34d399',
        behavior: { type: 'none' },
      },
      {
        id: 'qw_foot_fr',
        name: 'Pied Avant-Droit',
        position: { x: 505, y: 490 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 0.4,
        radius: 12,
        isPinned: false,
        color: '#34d399',
        behavior: { type: 'none' },
      },
      {
        id: 'qw_foot_rl',
        name: 'Pied Arrière-Gauche',
        position: { x: 285, y: 490 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 0.4,
        radius: 12,
        isPinned: false,
        color: '#34d399',
        behavior: { type: 'none' },
      },
      {
        id: 'qw_foot_rr',
        name: 'Pied Arrière-Droit',
        position: { x: 312, y: 490 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 0.4,
        radius: 12,
        isPinned: false,
        color: '#34d399',
        behavior: { type: 'none' },
      },
    ],
    links: [
      { id: 'qw_spine', nodeAId: 'qw_chest', nodeBId: 'qw_pelvis', restLength: 90, stiffness: 180, damping: 12, width: 16, color: '#10b981' },
      { id: 'qw_link_tail', nodeAId: 'qw_pelvis', nodeBId: 'qw_tail', restLength: 60, stiffness: 100, damping: 6, width: 8, color: '#f43f5e' },
      { id: 'qw_link_fl', nodeAId: 'qw_chest', nodeBId: 'qw_foot_fl', restLength: 100, stiffness: 130, damping: 8, width: 8, color: '#34d399' },
      { id: 'qw_link_fr', nodeAId: 'qw_chest', nodeBId: 'qw_foot_fr', restLength: 100, stiffness: 130, damping: 8, width: 8, color: '#34d399' },
      { id: 'qw_link_rl', nodeAId: 'qw_pelvis', nodeBId: 'qw_foot_rl', restLength: 100, stiffness: 130, damping: 8, width: 8, color: '#34d399' },
      { id: 'qw_link_rr', nodeAId: 'qw_pelvis', nodeBId: 'qw_foot_rr', restLength: 100, stiffness: 130, damping: 8, width: 8, color: '#34d399' },
    ],
  },

  // Preset 6 : Blob Mou (Soft Body Jelly)
  jellyBlob: {
    id: 'jellyBlob',
    name: 'Blob Mou (Soft-Body)',
    schemaVersion: 1,
    nodes: [
      {
        id: 'jb_core',
        name: 'Noyau Vivant',
        position: { x: 400, y: 350 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 1.0,
        radius: 22,
        isPinned: false,
        color: '#f43f5e',
        hasEye: true,
        behavior: { type: 'jiggle', strength: 1.2, damping: 0.6 },
      },
      {
        id: 'jb_p0',
        name: 'Membrane Haut',
        position: { x: 400, y: 295 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 0.4,
        radius: 16,
        isPinned: false,
        color: '#fb7185',
        behavior: { type: 'none' },
      },
      {
        id: 'jb_p1',
        name: 'Membrane Haut-Droit',
        position: { x: 448, y: 322 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 0.4,
        radius: 16,
        isPinned: false,
        color: '#fb7185',
        behavior: { type: 'none' },
      },
      {
        id: 'jb_p2',
        name: 'Membrane Bas-Droit',
        position: { x: 448, y: 378 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 0.4,
        radius: 16,
        isPinned: false,
        color: '#fb7185',
        behavior: { type: 'none' },
      },
      {
        id: 'jb_p3',
        name: 'Membrane Bas',
        position: { x: 400, y: 405 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 0.4,
        radius: 16,
        isPinned: false,
        color: '#fb7185',
        behavior: { type: 'none' },
      },
      {
        id: 'jb_p4',
        name: 'Membrane Bas-Gauche',
        position: { x: 352, y: 378 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 0.4,
        radius: 16,
        isPinned: false,
        color: '#fb7185',
        behavior: { type: 'none' },
      },
      {
        id: 'jb_p5',
        name: 'Membrane Haut-Gauche',
        position: { x: 352, y: 322 },
        velocity: { x: 0, y: 0 },
        acceleration: { x: 0, y: 0 },
        mass: 0.4,
        radius: 16,
        isPinned: false,
        color: '#fb7185',
        behavior: { type: 'none' },
      },
    ],
    links: [
      // Anneau externe
      { id: 'jbl_ring_01', nodeAId: 'jb_p0', nodeBId: 'jb_p1', restLength: 55, stiffness: 180, damping: 10, width: 14, color: '#fb7185' },
      { id: 'jbl_ring_12', nodeAId: 'jb_p1', nodeBId: 'jb_p2', restLength: 55, stiffness: 180, damping: 10, width: 14, color: '#fb7185' },
      { id: 'jbl_ring_23', nodeAId: 'jb_p2', nodeBId: 'jb_p3', restLength: 55, stiffness: 180, damping: 10, width: 14, color: '#fb7185' },
      { id: 'jbl_ring_34', nodeAId: 'jb_p3', nodeBId: 'jb_p4', restLength: 55, stiffness: 180, damping: 10, width: 14, color: '#fb7185' },
      { id: 'jbl_ring_45', nodeAId: 'jb_p4', nodeBId: 'jb_p5', restLength: 55, stiffness: 180, damping: 10, width: 14, color: '#fb7185' },
      { id: 'jbl_ring_50', nodeAId: 'jb_p5', nodeBId: 'jb_p0', restLength: 55, stiffness: 180, damping: 10, width: 14, color: '#fb7185' },
      // Rayons radiaux vers le noyau
      { id: 'jbl_rad_0', nodeAId: 'jb_core', nodeBId: 'jb_p0', restLength: 55, stiffness: 140, damping: 8, width: 10, color: '#f43f5e' },
      { id: 'jbl_rad_1', nodeAId: 'jb_core', nodeBId: 'jb_p1', restLength: 55, stiffness: 140, damping: 8, width: 10, color: '#f43f5e' },
      { id: 'jbl_rad_2', nodeAId: 'jb_core', nodeBId: 'jb_p2', restLength: 55, stiffness: 140, damping: 8, width: 10, color: '#f43f5e' },
      { id: 'jbl_rad_3', nodeAId: 'jb_core', nodeBId: 'jb_p3', restLength: 55, stiffness: 140, damping: 8, width: 10, color: '#f43f5e' },
      { id: 'jbl_rad_4', nodeAId: 'jb_core', nodeBId: 'jb_p4', restLength: 55, stiffness: 140, damping: 8, width: 10, color: '#f43f5e' },
      { id: 'jbl_rad_5', nodeAId: 'jb_core', nodeBId: 'jb_p5', restLength: 55, stiffness: 140, damping: 8, width: 10, color: '#f43f5e' },
    ],
  },
};

